### ISSUE TITLE
commentaire week 2

### ISSUE THREAD

**Issue by CodeboxxCoaches** [WillJacques/Rocket_Elevators_Controllers#1]
Tu as les bonne pratiques tout le long de tes codes 
Hésite pas a plus commenter ton code pour expliquer tes classe et /ou function 
Ton readme a été updater selon ce qui a été fait cette semaine 
Tres bon projet 
Bravo pour l'interface

**Comment by WillJacques** [comment]
Merci beaucoup ! Bonne semaine !
